go=0
xpeff=0
alarm[0]=30
black_alpha=0
white_alpha=0
normal_alpha=1
image_speed=0
instance_create_depth(x,y-(sprite_height/2),depth,effect_utraexp)
frame=0
framespd=0
out=0
global.canmove=0
if playerparent.free=false {playerparent.sprite_index=playerparent.zstand}
music_out=1
ratio=0
circle=0
circle_outline=1
sprite_index1=noone
sprite_index2=noone
sprite_index3=noone
sprite_x1=0
sprite_y1=0
sprite_x2=0
sprite_y2=0
sprite_x2=0
sprite_y2=0
sprite_a1=0
sprite_a2=0
sprite_a3=0
sprite_i1=0
sprite_i2=0
sprite_i3=0

