/// @description Inserte aquí la descripción
// Puede escribir su código en este editor
sprite_index=spr_solar_intro
image_index=0
ef_spr=spr_solar_xtreme_charge

if present_mav.finta=0
{
	ef=instance_create_depth(x,y-hsize,depth+0.5,obj_effect)
	ef.sprite_index=spr_imploth

	i=0
	if mode=1
	{
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=45+i
		disp.image_angle=45+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		i+=90
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=45+i
		disp.image_angle=45+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		i+=90
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=45+i
		disp.image_angle=45+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		i+=90
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=45+i
		disp.image_angle=45+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		mode*=-1
	}
	else
	{
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=0+i
		disp.image_angle=0+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		i+=90
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=0+i
		disp.image_angle=0+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		i+=90
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=0+i
		disp.image_angle=0+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		i+=90
		disp=instance_create_depth(x,y-hsize,depth+0.5,armored_sht)
		disp.direction=0+i
		disp.image_angle=0+i
		disp.speed=6
		disp.sprite_index=ef_spr
		disp.image_index=4
		disp.image_speed=0
		mode*=-1
	}
}