/// @description Inserte aquí la descripción
// Puede escribir su código en este editor
instance_deactivate_all(true)
instance_activate_region(__view_get( e__VW.XView, 0 )-200,__view_get( e__VW.YView, 0 )-240,__view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 )+200,__view_get( e__VW.YView, 0 )+__view_get( e__VW.HView, 0 )+250,true)
instance_activate_object(PersistentVars)
instance_activate_object(playerparent)
instance_activate_object(objGame)
instance_activate_object(objDisplay)
instance_activate_object(objJukebox)
instance_activate_object(objControl)
instance_activate_object(obj_palette_manager)
instance_activate_object(ob_lighting)
instance_activate_object(oWater)
instance_activate_object(oCalor)
instance_activate_object(DrawCbar)
instance_activate_object(DrawMoney)
instance_activate_object(objDraw)
instance_activate_object(Obj_BlackWindow)
instance_activate_object(objchargue)
instance_activate_object(View)
instance_activate_object(ob_pausemenu)
instance_activate_object(menubackground)
instance_activate_object(zero_shadow)
instance_activate_object(obj_roomchooser)
instance_activate_object(obj_ahera_hole)
instance_activate_object(puas)
instance_activate_object(falldead)
instance_activate_object(obj_rain)
instance_activate_object(obj_blockSolid)
instance_activate_object(obj_tilefactory)
instance_activate_object(obj_geemel_shuriken)
instance_activate_object(obj_geemel_shuriken2)
instance_activate_object(obj_trailadv)
instance_activate_object(obj_sombrapreset)
instance_activate_object(ob_effect_capsule_thunder)